name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint .
        ...

    - name: Lint with black
      run: |
        pip install black
        black .
        ...

    - name: Lint with isort
      run: |
        pip install isort
        isort .
        ...

    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle .
        ...

    - name: Lint with mypy
      run: |
        pip install mypy
        mypy .
        ...
